import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "@/app/api/uploadthing/core";
import { ModalProvider } from "@/components/providers/modal-provider";
import { SocketProvider } from "@/components/providers/socket-provider";
import { QueryProvider } from "@/components/providers/query-provider";
import { SocketStatus } from "@/components/socket-status";

// Thêm cấu hình dynamic 
export const dynamic = "force-dynamic";

const font=Open_Sans({subsets:['latin']})

export const metadata: Metadata = {
  title: "Team Chat Application",
  description: "Generated by create next app",
};

function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={cn(font.className,"bg-white dark:bg-[#313338]")}>
        <div className="flex flex-col items-center justify-center h-screen">
          <h2 className="text-xl font-bold mb-4">Something went wrong!</h2>
          <button
            className="px-4 py-2 bg-indigo-500 hover:bg-indigo-600 text-white rounded"
            onClick={() => reset()}
          >
            Try again
          </button>
        </div>
      </body>
    </html>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={cn(font.className,"bg-white dark:bg-[#313338]")}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false} storageKey="discord-theme"
        >
          <NextSSRPlugin
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <SocketProvider>
          <ModalProvider/>
          <QueryProvider>
            {children}
            <SocketStatus />
          </QueryProvider>
        </SocketProvider>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
